theme: jekyll-theme-cayman

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-93886808-1

gtag:
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-93886808-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-93886808-1');
</script>
